---

version: 3

vars:
  PWD:
    sh: pwd
  DEPLOY_CONTAINER_NAME: "deploy-container"
  DEPLOY_IMAGE_NAME: "kirillsilianov/deploy-image"
  DEPLOY_IMAGE_VERSION: "2.1"
  DEPLOY_IMAGE: "{{ .DEPLOY_IMAGE_NAME }}:{{ .DEPLOY_IMAGE_VERSION }}"

tasks:
  .set_private_key_mode:
    cmd: "chmod 0600 {{ .PWD }}/configuration/private_key.pem"

  .pre:
    deps:
      - ".set_private_key_mode"

  .run_deploy_container:
    cmds:
      - docker container stop {{ .DEPLOY_CONTAINER_NAME }} || true
      - docker container rm {{ .DEPLOY_CONTAINER_NAME }} || true
      - |
        docker run -d \
        -v {{ .PWD }}/configuration:/workdir \
        -v {{ .PWD }}/ansible.cfg:/etc/ansible/ansible.cfg \
        -v {{ .PWD}}/.users.yaml:/workdir/users.yaml \
        --env-file {{ .PWD }}/.env \
        --name {{ .DEPLOY_CONTAINER_NAME }} {{ .DEPLOY_IMAGE }} tail -f /dev/null
      - docker container exec -it {{ .DEPLOY_CONTAINER_NAME }} ansible-galaxy install -r requirements.yaml

  .stop_deploy_container:
    cmds:
      - docker container stop {{ .DEPLOY_CONTAINER_NAME }}
      - docker container rm {{ .DEPLOY_CONTAINER_NAME }}

  lint:
    cmd: |
      docker run -it --rm \
      -v {{ .PWD }}/configuration:/workdir \
      -v {{ .PWD }}/ansible-lint.yaml:/ansible-lint.yaml \
      --name {{ .DEPLOY_CONTAINER_NAME }} \
      {{ .DEPLOY_IMAGE }} ansible-lint -c /ansible-lint.yaml

  run:
    vars:
      TAGS: ""
    deps:
      - .pre
      - .run_deploy_container
    cmds:
      - |
        docker container exec -it {{ .DEPLOY_CONTAINER_NAME }} \
        ansible-playbook /workdir/deploy.yaml -i /workdir/inventory.yaml --extra-vars @users.yaml {{ .TAGS }}
      - defer:
          task: .stop_deploy_container
