---

server:
  hosts:
    node:
      ansible_host: "{{ lookup('ansible.builtin.env', 'SSH_HOST') }}"
      ansible_port: "{{ lookup('ansible.builtin.env', 'SSH_PORT') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'SSH_USER') }}"
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'SSH_BECOME_PASS') }}"
      ansible_ssh_private_key_file: "/workdir/private_key.pem"
      ansible_python_interpreter: /usr/bin/python3
