---

collections:
  - name: community.docker
  - name: community.mongodb

roles:
  - name: docker
    src: https://github.com/KirillSilianovO/ansible_role_docker
    version: "0.0.3"

  - name: traefik
    src: https://github.com/KirillSilianovO/ansible_role_traefik
    version: "0.0.3"
